### ISSUE TITLE
Map view when not tracking feature

### ISSUE THREAD

**Issue by hieu-van** [nguillaumin/osmtracker-android#104]
Hi !
I've used OSMTracker for a long time and I found it was such a great app. How about you adding map view feature ? It would be nice because I wouldn't have to open up web browser and go to openstreetmap.org . Just a minor suggestion
Cheers ;)

**Comment by nguillaumin** [comment]
Thanks, I'm not sure what you mean, there's already a map view? See the [screenshot from the wiki](https://github.com/nguillaumin/osmtracker-android/wiki) for instance?

**Comment by hieu-van** [comment]
Ah, I meant to be able to open the map even when not recording a track

**Comment by nguillaumin** [comment]
Ah right. I think that's unlikely to happen, because there are already apps that do that a lot better than I could do, like [OSMAnd](http://osmand.net/)...

**Comment by hieu-van** [comment]
I got it :)
