### ISSUE TITLE
Icons do not show up in custom preset

### ISSUE THREAD

**Issue by nlehuby** [nguillaumin/osmtracker-android#105]
I would like to add custom images to my buttons in my preset but they are not displayed.

I've tried : 
* svg images
* png images
* using the default layout images

Here is my preset : 

```xml
<layouts>
 <layout name="root">
   <row>
   <button type="tag" label="Poteau d'arrêt_" icon="pole.svg" />
   <button type="tag" label="Poteau d'arrêt" icon="shelter.png" />
   <button type="tag" label="Abribus" icon="button_misc_shelter.svg"/>
  </row>
     <row> (...) </row>
 </layout>
</layouts>

```
Here is the content of my layouts folder : 
.
├── my_layout.xml
├── pole.svg
└── shelter.png

Thanks in advance for your support.

**Comment by nguillaumin** [comment]
Hi,

SVG will definitely not work, but PNG should. I tried it with your test layout and a sample PNG image, and it works for me:

![screenshot from 2017-08-06 12-22-24](https://user-images.githubusercontent.com/762512/29006304-107f4b74-7aa2-11e7-90d0-2b8c1a2e6312.png)

Perhaps try with a different PNG image, maybe the one you're using is "special" in some way? If you attach it here I can give it a try.

**Comment by nlehuby** [comment]
ok, you are right, it seems ok with photos (PNG and JPG).
I was trying with icons exported from svg (for instance this one in png did not work : https://openclipart.org/detail/63457/bus-stop)

Thank you for your help 👍
