### ISSUE TITLE
Waypoints should be uploaded along with trackpoints

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#112]
http://learnosm.org/en/mobile-mapping/osmtracker/ says

Caution, do not delete your track yet. You have only uploaded the basic
trace and not the waypoints, photographs etc. Retain everything until it
is transferred to a computer for editing purposes.

https://wiki.openstreetmap.org/wiki/Upload_Waypoints
says one can upload waypoints along with trackpoints.

Therefore the OSMtracker documentation should document just what gets uploaded.
1. Trackpoins
2. Waypoints?
3. Voice notes?
4. Photos?
5. Etc.

And if waypoints aren't currently getting uploaded, they should be.

**Comment by nguillaumin** [comment]
I'm not the author of these docs, and personally I think that what happens is obvious enough. OpenStreetMap itself only cares about the track itself as far as I know (trackpoint + waypoints), and not the pictures, recordings or other media.

> And if waypoints aren't currently getting uploaded, they should be.

Well, perhaps you should check first before reporting an issue :wink: What's the point of raising an issue if you haven't event checked there's a problem in the first place? I feel it's a bit wasteful both for you and me.
The track file (GPX) is uploaded, and it contains both waypoints and trackpoints.

If you think these wikis are wrong / misleading, feel free to update them as you see fit, but I have nothing to do with them. Also if you want to write something regarding this I'd be happy to take it and put it under a new page in the OSMTracker project wiki. Just put it in a comment here and I'll copy/paste it into a page.

**Comment by jidanni** [comment]
OK added https://wiki.openstreetmap.org/w/index.php?title=OSMTracker_(Android)&diff=1508264&oldid=1490640
