### ISSUE TITLE
Don't call it "OSM Tracker for Android". Just call it OSM Tracker or OSMTracker.

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#118]
Don't call it "OSM Tracker for Android".
No other app adds the words "for Android" to the app name.

Go ahead and look in the Launcher. No other app has that added to the
name, making the name overflow in the Launcher. Also on Google Play no
other app adds those words.

And see you are the only Android app with the name OSM Tracker so there
is no conflict,
https://play.google.com/store/search?q=OSMTracker&c=apps

You might say what about the conflict on
https://wiki.openstreetmap.org/wiki/OSMtracker

Well the Windows Mobile version is for Windows Mobile and is no longer
maintained, and https://en.wikipedia.org/wiki/Windows_Mobile says
Windows Mobile has been deprecated.

**Comment by nguillaumin** [comment]
Hm no I'd rather not, since I hear there has been complaints from the Windows Mobile authors in the past, I'd prefer not to stir the pot. Plus I suspect renaming an app. on the Play store is a hassle...

**Comment by jidanni** [comment]
Maybe there is an option to make its display name other than its official name.
