### ISSUE TITLE
Add units to the numbers on the sending track screen.

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#124]
Add units to the numbers on the sending track screen. For example "bytes".

**Comment by nguillaumin** [comment]
Hard to do, because they're actually various things (track point, way points, etc.). I think the progress bar is good enough for now, but I won't object if someone wants to improve it.

**Comment by jidanni** [comment]
(OK but I never imagined it would be a mixed statistic. Maybe say
"items" or "combined items".
And actually I hardly ever see any progress bar. It immediately goes to
2345678/2345678 and just stays that way for a long time, until finally
some other message and then a success message appears.)
