### ISSUE TITLE
Porting to iOS?

### ISSUE THREAD

**Issue by Sidapo** [nguillaumin/osmtracker-android#132]
This app is fantastic. Sadly there is no equivallent for iOS. Has anyone thought about porting the app to iOS? I have no idea if this is possible or how labor intensive this would be, but it would be very great to have on iOS.

**Comment by nguillaumin** [comment]
I think it would have to be a complete rewrite, since there's no way to port an app from Android to IOS that I know of...

**Comment by Sidapo** [comment]
That's a shame. Thanks for clarifying though!
