### ISSUE TITLE
Allow keeping old tile cache for longer time

### ISSUE THREAD

**Issue by sneetsher** [nguillaumin/osmtracker-android#47]
I used to map for OSM in Sahara area with a limited Internet access.

There is nothing  on the ground to reference to like buildings, trees... Topographic map as background is best. However, I always loose them after relatively  short time, zooming out/in somewhere else.

Is possible to add tile cache folder to SD storage with predefined max size ex:100MB and never delete it, if it does not go over max size or unavailable Internet source to update them?

**Comment by nguillaumin** [comment]
Hi,

OSMTracker doesn't support that directly, but it's using [osmdroid](https://github.com/osmdroid/osmdroid) for the map background, so you'd have to investigate how to do offline tiles with this library. There are some guides online like: http://www.haakseth.com/?p=30
