### ISSUE TITLE
Current location icon on track display is too large

### ISSUE THREAD

**Issue by sneetsher** [nguillaumin/osmtracker-android#48]
That guy with yellow clothes is always standing in my map, who is used to show the current/last recorded point is too large and unnecessary covering my track. Could any one please tell him to go home?

If it is made transparent, just small ball point or a pin shape, it will much better.
 
![screenshot_2015-08-24-20-58-08](https://cloud.githubusercontent.com/assets/1183049/9451521/123f27fe-4aa7-11e5-88af-5635f34a28f6.png)

**Comment by nguillaumin** [comment]
I'd happily take a patch for this. I'm unlikely to implement it myself. Feel free to re-open with a patch, thanks!
