### ISSUE TITLE
Display distance

### ISSUE THREAD

**Issue by petemadsen** [nguillaumin/osmtracker-android#50]
A feature request: next to waypoints & co one could display the distance. So, a little more stats about a track. Thx.

**Comment by nguillaumin** [comment]
Thanks, I'll happily take a patch for that, but I won't be able to implement it by myself.

In the meantime I'll close it as I'm trying a more aggressive and honest way to handle issues / feature request (close them honestly rather than letting them rot for years as before).

**Comment by petemadsen** [comment]
I will try to find some time to implement it myself. Initially, I had some issues with importing the project in the studio.

**Comment by Forgen** [comment]
Wouldn't it be better to leave them open for some longer time period?  This sounds like something I'd like to try, and having a 'wish list' somewhere for folks like me to look for ideas to contribute.   Any ideas or better place for this kind of thing?

**Comment by nguillaumin** [comment]
Hi, that's what I used to do when the issues were on Google Code and I ended up with 200+ opened issues (some of them for a few years) that were hard to navigate, so I'm trying something different this time.
