### ISSUE TITLE
Make it possible to customize special buttons label

### ISSUE THREAD

**Issue by naoliv** [nguillaumin/osmtracker-android#51]
While https://github.com/nguillaumin/osmtracker-android/wiki/Custom-buttons-layouts says:

`For special buttons like voicerec, picture or textnote the label is automatically retrieved from the application string resources and cannot be changed.`

It would be good to have a way to customize their values.
For example, I am trying to get a smaller customized layout and "Gravação de voz" (the Portuguese translation for `voicerec`) is just too wide.

**Comment by nguillaumin** [comment]
Hi, I'd happily take a patch for that but I won't have time to implement it myself.
