### ISSUE TITLE
Explain the red dot on the UI

### ISSUE THREAD

**Issue by jasonwinget** [nguillaumin/osmtracker-android#52]
To the right of the signal strength meter bars on the UI there is a red dot  It doesn't turn red when you start recording, it turns red later at some other time.  There is no documentation and no overt reason for the dot to the user. Describe the function on the UI, use a different icon, etc.

**Comment by nguillaumin** [comment]
Hi, I'd happily take a patch to change the behaviour. Alternatively I think you might be able to suggest changes to the Wiki pages either directly or if not (I'm not very familiar with how forking Wikis work on GitHub) feel free to suggest them here and I'll add them to the doc.

Cheers!
