### ISSUE TITLE
Navigating between activities may cause OSMTracker to continue track recording

### ISSUE THREAD

**Issue by volchanetskiy** [nguillaumin/osmtracker-android#53]
Steps to reproduce:
1. Start **OSMTracker**
2. Touch **New track**. TrackLogger activity will appear.
3. From the menu select **Waypoints** (or Display track/Settings/About)
4. Return to TrackLogger activity by touching the **status bar notification**.
5. Touch **Stop & save**. The activity will be closed. Waypoint list will come back.
6. Touch **back** button. TrackLogger activity will appear and continue recording the track.
Version: 0.6.11

**Comment by nguillaumin** [comment]
Hi, fair enough I can see how that can happen. I'm unlikely to fix it though as I don't have much time to work on the app. these days, but I'd happily take a merge request for it.
