### ISSUE TITLE
[Feature request] Integrate offline maps

### ISSUE THREAD

**Issue by twzkxkan** [nguillaumin/osmtracker-android#54]
Would make the app more useful in situations where tiles cannot be downloaded.

One I know of is [maps.me API](https://github.com/mapswithme/api-android) which requires [maps.me](https://github.com/mapsme/omim) to be installed.

There may be others as well.

**Comment by Forgen** [comment]
++1!  I volunteer to help

**Comment by nguillaumin** [comment]
Hi, there is some information in #47. Happy to take a patch or a wiki page explaining how to prepare a tileset, assuming you find how ;)
