### ISSUE TITLE
Ability to upload waypoints to OSMTracker, so the app can be used like a GPS.

### ISSUE THREAD

**Issue by techlady** [nguillaumin/osmtracker-android#63]
If anyone is working on this, it would make the app very useful.

**Comment by nguillaumin** [comment]
Hi, I'm not sure I understand, could you expand a bit what you mean, and describe how the feature would work?

**Comment by techlady** [comment]
I have a database of points, and sometimes I want to go to a point that I may not have visited before. It would be great if Tracker provided a way to guide me to those points. 
However, having posted the question, I discovered later that I could add points to OSMAnd+. You can add them as waypoints or destinations. Maybe, OSMAnd is really what I should use. I do like using Tracker to keep track of my own tracks. I especially like the ability to link the tracks to pictures.

**Comment by nguillaumin** [comment]
Yeah I think OMSTracker fits a different purpose, it's not really intended to do routing.
