### ISSUE TITLE
Ignore GPS clock not working

### ISSUE THREAD

**Issue by ellyhiby** [nguillaumin/osmtracker-android#65]
Ticking the option to 'ignore GPS clock and use Android clock for timestamps' in the settings menu appears to make no difference to the timestamps recorded in the gpx file - they are recorded at GMT regardless of whether this option is selected or not. The gpx filename takes the time from the Android device, but the timestamp associated with each event recorded is always GMT.

This becomes a problem when using OSMtracker early morning in Nepal as the events appear to have been recorded late at night the previous day as opposed to early morning in Nepal.

**Comment by nguillaumin** [comment]
Hi,

This option doesn't really affect the timezone, it's more about reading the date from the GPS chip, or from the OS when recording a datapoint. In the GPX file the times are always [forced to UTC](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/gpx/ExportTrackTask.java#L122). There's no option to change that, but I'd take a pull request if somebody is keen to implement it ;)

Nico
