### ISSUE TITLE
Contribution OSMTracker

### ISSUE THREAD

**Issue by anamak** [nguillaumin/osmtracker-android#72]
Hello, I am a student of the National University of Comahue located in the city of Neuquén (Patagonia), Argentina. I'm currently pursuing a career course for Technician Management Systems and Free Software.
I work on a project of Libre Software because It is a course requirement (course: Libre Software) in which I have to collaborate in a libre project.
So the project that I chose is OSMTracker. I think I can contribute with streets of my town that have wrong name or no name at all..
I hope my contribution be useful for your project.
Best Regard
Anahi

**Comment by nguillaumin** [comment]
Hi,

I'm afraid you're confusing OSMTracker the application, with OpenStreetMap the project. This repository is about the Android application, to which you can contribute to the development by coding, if you want to. If you're interested in contributing to the map itself, check out the OpenStreetMap wiki: https://wiki.openstreetmap.org/wiki/Main_Page

Nicolas
