### ISSUE TITLE
Need way to stop recording a track

### ISSUE THREAD

**Issue by bdiscoe** [nguillaumin/osmtracker-android#76]
When recording a track, there is no way in the UI to stop recording.  The back button doesn't work; it keeps recording in the background.  I looked all over the GUI, and ultimately had to kill the app to get it to stop.  This is a huge glaring flaw.  Can't there simply be a nice clear button somewhere that says "Stop"?

**Comment by nguillaumin** [comment]
Hi, there is, in the menu, "Stop recording" I believe?

**Comment by bdiscoe** [comment]
No, there is no such command in the menu.  The menu contains four items:
1. Waypoints
2. Display track
3. Settings
4. About

There is no way to stop recording.  This really needs to be addressed.

**Comment by nguillaumin** [comment]
It depends on the Android version, on recent ones to stop tracking there's the save icon on the top right corner, next to the menu.

![stop1](https://cloud.githubusercontent.com/assets/762512/20033327/2725c2dc-a35b-11e6-9a01-9bfb9dde6b0c.png)

Alternatively on the track list, you can do a long-press and there's a "stop tracking" entry.

![stop2](https://cloud.githubusercontent.com/assets/762512/20033331/2e80b3ac-a35b-11e6-806c-f3b7eb29def7.png)

If you believe the UI can be improved, I'll happily take a pull request for that.

**Comment by bdiscoe** [comment]
Oh wow, OK.  The long press.  I don't think I would ever have found that without documentation.

After using the application for a while, I think I've figured out the primary GUI problem, and a solution.  Tracks are always saved as they are recorded, so there is no need for a "save" command.  The only need is for a "stop recording".  There is already a button on the main page which does a stop, but it has a "floppy disk" icon, which universally means "save".  In GUIs, "stop" is always represented differently than "save".  So, if the icon is simply changed from a "floppy disk" to a "stop" icon (for example, a red octagon, or a grey square), then it becomes obvious.
