### ISSUE TITLE
Unable to upload to OSM

### ISSUE THREAD

**Issue by jzlcdh** [nguillaumin/osmtracker-android#87]
![temp](https://cloud.githubusercontent.com/assets/6815174/25755454/ceca9b44-31cb-11e7-98da-0f330325d53f.jpeg)

OSM tracker v0.611 Android 4.4.2

I am unable to upload to OSM directly from Osmtracker.
Is there a log somewhere I should look for more details of the problem shown in the attached screenshot? If not any advice please?

**Comment by jzlcdh** [comment]
I tried "increase search radius" several times but got the same error.

**Comment by nguillaumin** [comment]
If you want to write something, I'd be happy to put it in the wiki. I can't do it easily as I'm not experiencing the issue myself...

**Comment by jzlcdh** [comment]
I guess you mean https://github.com/nguillaumin/osmtracker-android/wiki rather than  http://wiki.openstreetmap.org/wiki/OSMTracker_(Android)

If so the latter could maybe read Troubleshooting - please see https://github.com/nguillaumin/osmtracker-android/wiki

Troubleshooting
--------------------
Unable to upload to openstreetmap 
--------------------------------------------
1) Check your wireless or data connection is turned on
2) In Android settings>manage apps>OSM Tracker for Android click "clear defaults" (see https://github.com/nguillaumin/osmtracker-android/issues/68 if you want the technical details)

**Comment by nguillaumin** [comment]
Done: https://github.com/nguillaumin/osmtracker-android/wiki/Troubleshooting
