### ISSUE TITLE
Delete all tracks menu item too close to other menu items

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#89]
The delete all tracks menu item  is extremely dangerously close to the export all  tracks to GPX menu item. One fears that if one puts on's finger just a little too close, all will be lost. No I didn't dare try to test it to see what would happen. Maybe it really does have a confirmation question. But the user would be still so scared all the time.

**Comment by nguillaumin** [comment]
Hi, there's a [confirmation message](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/TrackManager.java#L204) indeed, so I think it's safe enough for now.
